name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Ensure resources directory exists
        run: mkdir -p ./src/main/resources

      - name: Make application.yml
        if: contains(github.ref, 'main')
        run: |
          touch ./src/main/resources/application.yml
          echo "${{ secrets.YML }}" > ./src/main/resources/application.yml
        shell: bash

      - name: Make application-db.yml
        if: contains(github.ref, 'main')
        run: |
          touch ./src/main/resources/application-db.yml
          echo "${{ secrets.YML_DB }}" > ./src/main/resources/application-db.yml
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker image build & Push
        run: |
          docker build --no-cache -t ${{ secrets.DOCKER_USERNAME }}/growplan .
          docker push ${{ secrets.DOCKER_USERNAME }}/growplan

      - name: Get GitHub IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ env.AWS_ROLE }}

      - name: Add Ip to SG
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 22
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            sudo docker ps
            sudo docker stop $(sudo docker ps -q)
            sudo docker rm $(sudo docker ps --filter 'status=exited' -q)
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/growplan
            sudo docker run -d -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/growplan
            sudo docker image prune -a -f

      - name: Revoke IP from SG
        run: |
          aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
